/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import ButtonAnim from "./script/views/ButtonAnim"
import ConvergeAdView from "./script/views/ConvergeAdView"
import ListLoopView from "./script/views/ListLoopView"
import GameOverView from "./script/views/GameOverView"
import WXLaunch from "./script/platform/wx/WXLaunch"
import MainView from "./script/views/MainView"
import SideAdView from "./script/views/SideAdView"
import WXRankView from "./script/views/rank/WXRankView"
import TipView from "./script/views/TipView"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="Launch.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/views/ButtonAnim.ts",ButtonAnim);
        reg("script/views/ConvergeAdView.ts",ConvergeAdView);
        reg("script/views/ListLoopView.ts",ListLoopView);
        reg("script/views/GameOverView.ts",GameOverView);
        reg("script/platform/wx/WXLaunch.ts",WXLaunch);
        reg("script/views/MainView.ts",MainView);
        reg("script/views/SideAdView.ts",SideAdView);
        reg("script/views/rank/WXRankView.ts",WXRankView);
        reg("script/views/TipView.ts",TipView);
    }
}
GameConfig.init();