/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package {
	import laya.utils.ClassUtils;
	import ButtonAnim;
	import ConvergeAd;
	import laya.display.Text;
	import laya.ui.WXOpenDataViewer;
	import GameFighting;
	import GameOverEndless;
	import game.button_anim;
	import GoldenEggView;
	import WXLaunch;
	import MainViewLandscape;
	import MainViewVertical;
	import RankItem;
	import RankView;
	import Resurgence;
	import TipView;
	/**
	 * 游戏初始化配置
	 */
	public class GameConfig {
		public static var width:int = 640;
		public static var height:int = 1136;
		public static var scaleMode:String = "fixedwidth";
		public static var screenMode:String = "none";
		public static var alignV:String = "top";
		public static var alignH:String = "left";
		public static var startScene:* = "Launch.scene";
		public static var sceneRoot:String = "";
		public static var debug:Boolean = false;
		public static var stat:Boolean = false;
		public static var physicsDebug:Boolean = false;
		public static var exportSceneToJson:Boolean = true;
		
		public static function init():void {
			//注册Script或者Runtime引用
			var reg:Function = ClassUtils.regClass;
			reg("ButtonAnim",ButtonAnim);
			reg("ConvergeAd",ConvergeAd);
			reg("laya.display.Text",Text);
			reg("laya.ui.WXOpenDataViewer",WXOpenDataViewer);
			reg("GameFighting",GameFighting);
			reg("GameOverEndless",GameOverEndless);
			reg("game.button_anim",button_anim);
			reg("GoldenEggView",GoldenEggView);
			reg("WXLaunch",WXLaunch);
			reg("MainViewLandscape",MainViewLandscape);
			reg("MainViewVertical",MainViewVertical);
			reg("RankItem",RankItem);
			reg("RankView",RankView);
			reg("Resurgence",Resurgence);
			reg("TipView",TipView);
		}
		GameConfig.init();
	}
}