/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import WXLaunch from "./script/platform/wx/WXLaunch"
import MainView from "./script/views/MainView"
import PromotionAnimation from "./script/views/PromotionAnimation"
import WXRankView from "./script/views/rank/WXRankView"
import TipView from "./script/views/TipView"
import ButtonAnim from "./script/views/ButtonAnim";
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="Launch.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/platform/wx/WXLaunch.ts",WXLaunch);
        reg("script/views/MainView.ts",MainView);
        reg("script/views/ButtonAnim.ts",ButtonAnim);
        reg("script/views/PromotionAnimation.ts",PromotionAnimation);
        reg("script/views/rank/WXRankView.ts",WXRankView);
        reg("script/views/TipView.ts",TipView);
    }
}
GameConfig.init();